name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Chạy khi push vào nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js (nếu deploy app Node.js)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Deploy to AWS EC2
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: "ec2-user"
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          
          # SSH vào server để pull code và restart app
          ssh -i private_key.pem -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            cd /var/www/khanhtc_node_app
          
            # Pull code mới nhất
            git pull origin main
          
            # Cài đặt dependencies
            npm install
          
            # Restart ứng dụng với PM2
            pm2 restart khanhtc_node_app || pm2 start server.js --name khanhtc_node_app
            pm2 save
          EOF
