name: Deploy Node.js App to AWS EC2

on:
  push:
    branches:
      - main  # Chạy workflow khi push lên branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to AWS EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: "ec2-user"
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            # Cập nhật môi trường & cài đặt phần mềm
            sudo yum -y update
            curl -sL https://rpm.nodesource.com/setup_20.x | sudo bash -
            sudo yum install -y nodejs git
            sudo npm install -g pm2@latest

            # Cấu hình thư mục ứng dụng
            sudo mkdir -p /var/www/khanhtc_node_app
            sudo chown -R ec2-user:ec2-user /var/www/khanhtc_node_app
            sudo chmod -R 755 /var/www/khanhtc_node_app

            # Xóa code cũ & clone repo mới
            cd /var/www/khanhtc_node_app
            if [ -d ".git" ]; then
              git reset --hard
              git pull origin main
            else
              git clone ${{ secrets.GIT_REPO_URL }} .
            fi

            # Đánh dấu thư mục Git là an toàn
            git config --global --add safe.directory /var/www/khanhtc_node_app

            # Cài đặt & chạy ứng dụng với PM2
            npm install
            pm2 restart khanhtc_node_app || pm2 start server.js --name khanhtc_node_app
            pm2 save
            pm2 startup systemd
          EOF
